### ISSUE TITLE
Large Stack Variables Error in Anchor 0.29.0

### ISSUE THREAD

**Issue by chenmoonmo** [solana-foundation/anchor#2835]
I encountered an error when I tried to compile my Solana program (https://github.com/chenmoonmo/anchor-dex):
Error: Function _ZN157_$LT$anchor_dex..instructions..init_pool..InitializePool$u20$as$u20$anchor_lang..Accounts$LT$anchor_dex..instructions..init_pool..InitializePoolBumps$GT$$GT$12try_accounts17hc6503ec5b47d6f18E Stack offset of 5672 exceeded max offset of 4096 by 1576 bytes, please minimize large stack variables

how can i fix it?

rustc 1.76.0
anchor-cli 0.29.0
solana-cli 1.18.3
solana-program 1.18.3

**Comment by acheroncrypto** [comment]
https://github.com/chenmoonmo/anchor-dex/blob/46f7a9b4a6f4332d3f476112c2c9de6e25b9a099/programs/anchor-dex/src/instructions/init_pool.rs#L17-L20

You can `Box` the `Mint` accounts.

**Comment by chenmoonmo** [comment]
After I do this, the error still appears, but when I import the code into solana playground, the compiled program can be called normally.

**Comment by acheroncrypto** [comment]
Does it only happen in `solana-cli 1.18`? Solana Playground has the same Anchor version but it's not on `solana-cli 1.18`.

Also, this error is more of a warning and usually doesn't cause runtime errors. Does it work if you test it locally?

**Comment by chenmoonmo** [comment]
In local testing the instruction is called correctly, but when I build and deploy to devnet the instruction is called with an error

**Comment by zfedoran** [comment]
Also seeing something similar but in a different place. 

`Error: Function _ZN112_$LT$solana_program..instruction..InstructionError$u20$as$u20$solana_frozen_abi..abi_example..AbiEnumVisitor$GT$13visit_for_abi17h31964a789f899580E Stack offset of 4504 exceeded max offset of 4096 by 408 bytes, please minimize large stack variables`

I suspect there is something up with the latest solana program or cli. I'm on `1.18.4`, going to try older versions...

**Comment by Bhargavamacha** [comment]
Hey @acheroncrypto we upgraded a different program to v29 and got a Stack offset exceeded max offset by a huge amount. Could the bumps change cause an increased stack usage by any chance?

**Comment by acheroncrypto** [comment]
Yes, the bumps change increased the stack usage slightly but it shouldn't be a huge amount. Did you also upgrade to `1.18` CLI? That also has some memory issues.

Some people have reported an issue regards to it but not a lot. Does https://github.com/coral-xyz/anchor/pull/2766 fix your issue?

**Comment by Bhargavamacha** [comment]
I did yeah, I haven't checked, will do and get back. Could it be possible the new struct is over allocating if you cross a threshold of accounts?

**Comment by acheroncrypto** [comment]
I think it may be getting multiple times since the fields are `u8`, which is `Copy`, and combined with a lot of accounts it could cause excessive stack usage.

**Comment by Bhargavamacha** [comment]
okay I will investigate a bit further and get back

**Comment by acheroncrypto** [comment]
Related: https://github.com/anza-xyz/agave/issues/252

**Comment by acheroncrypto** [comment]
Solana 1.18.8 includes fixes to memory related issues (https://github.com/anza-xyz/agave/pull/362).

Try to see if upgrading fixes this problem.

**Comment by chenmoonmo** [comment]
stack offset problems associated with bumps still exist

**Comment by ThallesP** [comment]
same here, i was getting some errors with stack size in 0.28.0 and thought of giving 0.29.0 a try again because someone told me that 0.29.0 reduces heap stack a little.

in 0.28.0 my stack would only exceed by 40 bytes or so
![image](https://github.com/coral-xyz/anchor/assets/76017384/cdbed5ac-beab-44fe-aa23-755a7bcfbb65)

in 0.29.0 it exceeds by a whopping 1368 bytes
![image](https://github.com/coral-xyz/anchor/assets/76017384/72a29bad-9bf1-4f50-9562-6e297a1af872)

and before we blame it in the handler, my entire handler is commented out, it just returns `Ok(())`.
And I'm on solana-cli 1.18.8
![image](https://github.com/coral-xyz/anchor/assets/76017384/0a137264-1284-4aa0-853b-210f1fa92bc0)

cc @chenmoonmo @acheroncrypto

**Comment by Bhargavamacha** [comment]
@acheroncrypto I dont think the issue is fixed in 1.18.8. Can you think of anything that changed in 1.18 that could be causing this

**Comment by belakm** [comment]
Same issue here, Boxing helps, but not enough

**Comment by etodanik** [comment]
We still get issues with `1.18.15`, so the fixes certainly didn't help

**Comment by jacobcreech** [comment]
With the 0.31 release, stack issues have mostly disappeared. I'm closing this issue for now.

**Comment by johnsaigle** [comment]
@jacobcreech any chance you could elaborate on this or link to relevant code changes?
