### ISSUE TITLE
IDL Generation Fails with Seeds Constraints Referencing Account Fields in Anchor 0.31.x (0.30 also)

### ISSUE THREAD

**Issue by ohgeebtw** [solana-foundation/anchor#3947]
## Bug Description

When using `seeds` constraints that reference account fields in `#[derive(Accounts)]` structs, IDL generation fails with `error[E0425]: cannot find value` during `anchor build`. The contract compiles successfully with `anchor build --no-idl` but fails when generating IDL.

## Error Message

```
error[E0425]: cannot find value `user` in this scope
  --> programs/groundzero_contract/src/account_types.rs:79:10
   |
79 | #[derive(Accounts)]
   |          ^^^^^^^^ not found in this scope
   |
   = note: this error originates in the derive macro `Accounts` (in Nightly builds, run with -Z macro-backtrace for more info)
```

## Steps to Reproduce

1. Create an Anchor project with version 0.31.x
2. Define an account struct with seeds constraint referencing another account field:

```rust
#[derive(Accounts)]
pub struct CreateBuyer<'info> {
    #[account(mut)]
    pub user: Signer<'info>,

    #[account(
        init,
        payer = user,
        space = 8 + 33,
        seeds = [b"buyerinfo", user.key().as_ref()],  // This line causes the error
        bump
    )]
    pub buyer: Account<'info, BuyerInfo>,

    pub system_program: Program<'info, System>,
}
```

3. Run `anchor build`
4. Build fails during IDL generation phase

## Expected Behavior

- Contract should build successfully with IDL generation
- Seeds constraints referencing account fields should work as documented
- IDL should properly reflect the account structure

## Actual Behavior

- Contract compiles fine with `anchor build --no-idl`
- IDL generation fails with "cannot find value" error
- Seeds constraints are not recognized during IDL build phase

## Environment

- **Anchor CLI Version**: 0.31.1
- **Anchor Lang Version**: 0.31.1
- **Rust Version**: 1.75.0 (also tested with 1.85.1)
- **Solana CLI Version**: Latest
- **OS**: Linux (Fedora 6.15.10-100.fc41.x86_64)

### Working Example (without seeds)
```rust
#[derive(Accounts)]
pub struct CreateBuyer<'info> {
    #[account(mut)]
    pub user: Signer<'info>,

    #[account(
        init,
        payer = user,
        space = 8 + 33
    )]
    pub buyer: Account<'info, BuyerInfo>,

    pub system_program: Program<'info, System>,
}
```

### Failing Example (with seeds)
```rust
#[derive(Accounts)]
pub struct CreateBuyer<'info> {
    #[account(mut)]
    pub user: Signer<'info>,

    #[account(
        init,
        payer = user,
        space = 8 + 33,
        seeds = [b"buyerinfo", user.key().as_ref()],  // Fails here
        bump
    )]
    pub buyer: Account<'info, BuyerInfo>,

    pub system_program: Program<'info, System>,
}
```

### 1. Instruction Parameter Approach (Also Fails)
```rust
#[derive(Accounts)]
#[instruction(user_key: Pubkey)]
pub struct CreateBuyer<'info> {
    #[account(mut)]
    pub user: Signer<'info>,

    #[account(
        init,
        payer = user,
        space = 8 + 33,
        seeds = [b"buyerinfo", user_key.as_ref()],  // Still fails
        bump
    )]
    pub buyer: Account<'info, BuyerInfo>,

    pub system_program: Program<'info, System>,
}
```

**Comment by 0x4nud33p** [comment]
Hi @ohgeebtw I’d like to contribute a fix for this. From my investigation, the problem is that IDL generation tries to evaluate seeds expressions literally, and fails when they reference other accounts (e.g. `user.key().as_ref()`).

I see two possible approaches:
 - Stringify seed expressions in IDL
 - Extend the IDL schema to support dynamic seeds
 
Which direction would you prefer me to take for this.

**Comment by akash-osec** [comment]
can you show whats in your `Cargo.toml` at root level?
Since i'm not able to reproduce this issue! also the issue is already seems to be fixed or not existed in current version.

you can also debug by adding some debug prints [here](https://github.com/solana-foundation/anchor/blob/7360dbba3afdea1f8486e2f86c0d50b0f2450111/lang/syn/src/idl/accounts.rs#L414)
```sh
$ ANCHOR_IDL_BUILD_RESOLUTION=TRUE cargo test __anchor_private_print_idl --features idl-build 2>&1 | grep "DEBUG:" | head -20
DEBUG: seed_str = "user.key().as_ref()"
DEBUG: components = ["user", "key()", "as_ref()"]
DEBUG: name = "user"
```

**Comment by ohgeebtw** [comment]
@Otter-0x4ka5h Here is my cargo.toml at root level.

Will add the logging to the idl build as soon as I can and report back. 

```
[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
```

**Comment by ohgeebtw** [comment]
# Instruction parameter (project_id) 
[ANCHOR DEBUG] seed_str: "project_id . as_ref ()"
[ANCHOR DEBUG] components: ["project_id ", " as_ref ()"]
[ANCHOR DEBUG] name: "project_id "
[ANCHOR DEBUG] Final SeedPath - name: "project_id ", subfields: []

# Account field (user)
[ANCHOR DEBUG] seed_str: "user . key () . as_ref ()"
[ANCHOR DEBUG] components: ["user ", " key () ", " as_ref ()"]
[ANCHOR DEBUG] name: "user "
[ANCHOR DEBUG] Final SeedPath - name: "user ", subfields: []

# Account field (payer)
[ANCHOR DEBUG] seed_str: "payer . key () . as_ref ()"
[ANCHOR DEBUG] components: ["payer ", " key () ", " as_ref ()"]
[ANCHOR DEBUG] name: "payer "
[ANCHOR DEBUG] Final SeedPath - name: "payer ", subfields: []

# Account field (buyer)
[ANCHOR DEBUG] seed_str: "buyer . key () . as_ref ()"
[ANCHOR DEBUG] components: ["buyer ", " key () ", " as_ref ()"]
[ANCHOR DEBUG] name: "buyer "
[ANCHOR DEBUG] Final SeedPath - name: "buyer ", subfields: []

---

The problem seems to have been caused by a whitespaces introducted by rusts tokenizer being preserved on the split '.' . 

The fix was simple, adding .trim(), so I went ahead and did it myself.

Created PR! 


Cheers everyone!

**Comment by akash-osec** [comment]
sorry, i'm still not able to reproduce the issue. i'm pretty sure that it has been fixed in current master branch.
Did the fix was produced by AI!! Also, can you please show us what's in your `programs/cargo.toml`?

**Comment by ohgeebtw** [comment]
@Otter-0x4ka5h 

```toml
[package]
name = "groundzero_subscription_contract"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "groundzero_subscription_contract"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-spl/idl-build"]


[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
chrono = "0.4.40"
```



What do you mean by "Did the fix was produced by AI!!" ? If you are asking if I am coding with AI support, the answer is yes, at IDE and Bash level. 
The debugging was also conducted under AI support for efficiency purposes, the problem was then identified by logging the flow as requested, the fix was implented and tested locally, build was successful after implementing the fix. 

The only thing `.trim()` does here is ensure subtle parsing errors are not possible, so no security risks should have been introduced, since `seed_str` comes directly from the compiler and is not user generated.

**Comment by ohgeebtw** [comment]
@jamie-osec @Otter-0x4ka5h 

After updating my rustc from 1.88.0-nightly to the newest one released yesterday 1.93.0 nightly, the problem was fixed. 
 
This means proc_macro2 on 1.88.0 was formatting token streams with trailing spaces (by mistake).


I would still recommend for us to add the `.trim()` call to the see path parsing on master branch as a preventive measure, since by doing so we are just assuring robustness of the code with nothing to loose.

**Comment by lunar-bard** [comment]
@ohgeebtw I'm having the same issue. I updated to rust to 1.93.0 (nightly-2025-11-05) but it didn't fix it.
My only way around it is `anchor build --no-idl` but I will need the IDL.

**Comment by ohgeebtw** [comment]
@0xBreath that is intresting, what version of anchor are you running, 0.31.X or 0.32.X ? 
I can provide you a forked version of your version with the fix implemented until my fix is merged into main (if it gets merged into main). 


@Otter-0x4ka5h @jamie-osec  Please consider adding the `.trim()` to ensure that even if the rust tokenizer   introduces trailing spaces, they are removed by default.

**Comment by lunar-bard** [comment]
@ohgeebtw 
rustc: 1.86.0 (05f9846f8 2025-03-31) or 1.93.0-nightly (c90bcb957 2025-11-06)
anchor: 0.31.1
solana: 2.3.0

cargo build-sbf works fine. 
it's just the idl build. 
and yes I have the idl-build feature in my program Cargo.toml like the issues and release notes said to do.

i shouldn't need to fork anchor if other people don't have this problem

UPDATE: 1.91.0 works! Don't know why

**Comment by ohgeebtw** [comment]
Yeah we need to add the trim to avoid the problems introduced by the different versions of the rust tokenizer.

**Comment by jamie-osec** [comment]
Closing given the above discussion, since Anchor now pins specific Rust toolchain versions. The `trim` solution is a bandaid fix on top of a hacky solution which isn't robust against string changes. A better fix would be to operate on the already parsed expression, or use `syn` to parse a `SeedPath` directly from the original token stream.
